apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: thinhnotes
        # The Github repository
        repo: gitopsatscale
        labels:
        - preview
  template:
    metadata:
      name: 'myapp-{{ .branch }}-{{ .number }}'
      labels:
        key1: '{{ index .labels 0 }}'
    spec:
      source:
        repoURL: https://github.com/thinhnotes/gitopsatscale
        targetRevision: '{{ .head_sha }}'
        path: ./app-of-apps/manifests/backend
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .branch }}-{{ .number }}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true