apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: thinhnotes
        repo: gitopsatscale
        labels:
        - preview
      requeueAfterSeconds: 5
  template:
    metadata:
      name: 'myapp-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: https://github.com/thinhnotes/gitopsatscale
        targetRevision: '{{ .head_sha }}'
        path: ./app-of-apps/manifests/backend
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .branch }}-{{ .number }}"
      syncPolicy: