apiVersion: v1
data:
  token: Z2l0aHViX3BhdF8xMUFCRFIyTVkwM0dzVDN1TTdHakNhX090VGRka3RKNHZ0clZFd3c4cEh3bk45bXhZc3o0ZDBnS0VhbXVOc2NKN0RHSktVWkNQSXcxbnZETExi
kind: Secret
metadata:
  creationTimestamp: null
  name: github-token
  namespace: argocd
