apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: thinhnotes
        repo: gitopsatscale
        tokenRef:
          secretName: repo-3369786262
          key: password
      requeueAfterSeconds: 5
  template:
    metadata:
      name: 'myapp-{{number}}'
    spec:
      source:
        repoURL: https://github.com/thinhnotes/gitopsatscale
        targetRevision: '{{ head_sha }}'
        path: ./app-of-apps/manifests/backend
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ number }}"
      syncPolicy:
