apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: thinhnotes
        repo: gitopsatscale
        #should create the token ref because of the not autozie just request limit api to github 
        #Error listing repos: error listing pull requests for
        #thinhnotes/gitopsatscale: GET
        #https://api.github.com/repos/thinhnotes/gitopsatscale/pulls?per_page=100:
        #403 API rate limit exceeded for xx.xx.xx.x. (But here's the good news:
        #Authenticated requests get a higher rate limit. Check out the
        #documentation for more details.) [rate reset in 23m13s]
        tokenRef:
          secretName: github-token
          key: token
        # this filter label for the PR request
        #labels:
        #- documentation
        # Include any pull request ending with "features". (optional)
        #filters:
        #- branchMatch: "features/*"
      requeueAfterSeconds: 5
  template:
    metadata:
      name: 'myapp-{{branch_slug}}{{number}}'
    spec:
      source:
        repoURL: https://github.com/thinhnotes/gitopsatscale
        targetRevision: '{{ head_sha }}'
        path: ./app-of-apps/manifests/backend
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{branch_slug}}{{ number }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      

